name: Deploy Azure Config
on:
    push:
      branches:
        - main
    pull_request:
        branches:
            - main
        types: [closed]
permissions:
      id-token: write
      contents: read
jobs:
  deploy_azure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fargate_config
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Set up Azure CLI'
      uses: azure/CLI@v2
      with:
          inlineScript: |
              az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              az configure --defaults location=centralus
    
    - name: Generate backend
      run: |
        cat <<EOF > backend.tf
        terraform {
            backend "azurerm" {
                resource_group_name  = "tfstate"
                storage_account_name = "nhterraformstate"
                container_name       = "terraform"
                key                  = "terraform.tfstate"
            }
        }
        EOF

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve